openapi: 3.0.4
info:
  title: echo-api-nano
  description: A service that returns the text passed in.
  termsOfService: https://ibm.com/terms/
  contact:
    name: Ricky Moorhouse
    url: www.ibm.com
    email: api-connect@ibm.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: '1'
servers:
  - url: https://apiconnect.automation.ibm.com
externalDocs:
  description: Find out more about IBM DataPower Nano Gateway
  url: https://ibm.com
tags:
  - name: echo
    description: Echo API
paths:
  /echo:
    get:
      description: Retrieve the details of your order.
      operationId: getEcho
      tags:
        - echo
      parameters:
        - name: text
          in: query
          description: Text to echo
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Echo text provided
