swagger: '2.0'
info:
  title: Echo API
  x-ibm-name: echo-api
  description: Simple Echo API
  version: 1.1.0
  contact:
    name: Ricky Moorhouse
    email: moorh@uk.ibm.com
host: $(catalog.host)
schemes: []
basePath: /public
produces:
  - application/json
security: []
parameters:
  text:
    name: text
    type: string
    required: false
    in: query
    description: Text passed in
definitions:
  responseObject:
    properties:
      text:
        type: string
paths:
  /echo:
    get:
      responses:
        '200':
          description: 200 OK
          schema:
            $ref: '#/definitions/responseObject'
      parameters:
        - $ref: '#/parameters/text'
    parameters:
      - type: string
        name: text
        in: query
        description: Text to echo
        required: true
